# Generated by Django 3.0.2 on 2020-01-12 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sector',
            fields=[
                ('idSector', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=10, unique=True)),
                ('region', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=25, unique=True)),
                ('contrasena', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='puntoRecoleccion',
            fields=[
                ('idPunto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('latitud', models.DecimalField(decimal_places=20, max_digits=30)),
                ('longitud', models.DecimalField(decimal_places=20, max_digits=30)),
                ('icono', models.CharField(max_length=50)),
                ('sumaCalificacion', models.IntegerField()),
                ('cantidadUsuarioCal', models.IntegerField()),
                ('idSector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionBD.sector')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionBD.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='noticiaTip',
            fields=[
                ('idNoticia', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('url', models.TextField()),
                ('tipoNoticia', models.CharField(max_length=100)),
                ('idSector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionBD.sector')),
            ],
        ),
        migrations.CreateModel(
            name='horarioRecoleccion',
            fields=[
                ('idPuntoHorario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dia', models.CharField(max_length=15)),
                ('hora', models.CharField(max_length=15)),
                ('idSector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionBD.sector')),
            ],
        ),
    ]
