# Generated by Django 3.0.2 on 2020-01-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cedula',
        ),
    ]
